### PR TITLE
Fix file names POF 2002

### PR DESCRIPTION
**Pull request by raphael-gouvea**
* outras depesas
* rendimentos

### CODE REVIEW

**Comment by raphael-gouvea** [comment]
Nicolas corrected the veiculos file name, but these other two were also wrong.

**Comment by lucasmation** [comment]
1st community contribution!!!, valeu @raphael-gouvea

**Comment by raphael-gouvea** [comment]
I was actually thinking about how I could contribute more because this is a great project! Giving my constraints at the moment, maybe I could continue contributing when spotting some bugs, but I was thinking that I could also help with other things like documentation, tutorial or webpage...

**Comment by lucasmation** [comment]
tks. No need now. We will review all these ( documentation, tutorial or
webpage) now in Oct, submit to cran and probably to a jounal in Nov/Dec

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-09-30 21:11 GMT-03:00 Raphael Gouvea <notifications@github.com>:

**Pull request merged**
