### PR TITLE
update SISOB dictionaries

### PR DESCRIPTION
**Pull request by nicolassoarespinto**

### CODE REVIEW

**Comment by lucasmation** [comment]
@nicolassoarespinto , this did not solve the problem. 

read_SISOB("obitos", 200103) %>% View()

is still all wrong, reading with the old dictionary

**Comment by nicolassoarespinto** [comment]
Here i see:


```
> get_import_dictionary("SISOB",200301, "obitos")
  int_pos    var_name  x label length decimal_places fin_pos col_type CHAR
1       1    NOME_SCO NA           76              0      76        c TRUE
2      77 DT_NASC_SCO NA            8              0      84        c TRUE
3      85 DT_NASC_SCO NA            8              0      92        c TRUE
4      93     N_BENEF NA           10              0     102        c TRUE
5     103     CPF_SCO NA           11              0     113        c TRUE
6     114     MAE_SCO NA           32              0     145        c TRUE
7     146     ID_CART NA            9              0     154        c TRUE
> get_import_dictionary("SISOB",201101, "obitos")
   int_pos     var_name  x label length decimal_places fin_pos col_type CHAR
1        1        LIVRO NA            6              0       6        c TRUE
2        7        FOLHA NA            5              0      11        c TRUE
3       12        TERMO NA           10              0      21        c TRUE
4       22 DT_LAVRATURA NA            8              0      29        c TRUE
5       30      N_BENEF NA           10              0      39        c TRUE
6       40     NOME_SCO NA           76              0     115        c TRUE
7      116      MAE_SCO NA           32              0     147        c TRUE
8      148  DT_NASC_SCO NA            8              0     155        c TRUE
9      156     DT_OBITO NA            8              0     163        c TRUE
10     164      CPF_SCO NA           11              0     174        c TRUE
11     175      NIT_SCO NA           11              0     185        c TRUE
12     186      TP_CART NA            1              0     186        c TRUE
13     187      ID_CART NA            1              0     187        c TRUE
```



Have you pulled the repository from RStudio? And used `devtools::load_all()` before trying?

**Comment by nicolassoarespinto** [comment]
@lucasmation i just noted that the above dictionary is still wrong( there is two DT_NASC_SCO), just a minute and will upload a new version.

**Comment by lucasmation** [comment]
I now see the correct dictionary for 200103:200308, tks

2016-10-13 14:18 GMT-03:00 nicolassoarespinto <notifications@github.com>:

**Pull request merged**
